[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["tmvfb <darestade@gmail.com>"]
readme = "README.md"
packages = [{include = "page_analyzer"}]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2.3"
python-dotenv = "^0.20.0"
gunicorn = "^20.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
